SpyglassMC/Spyglass

- src/parsers/LineParser.ts
- src/parsers/LiteralArgumentParser.ts
- src/parsers/NbtTagArgumentParser.ts
- src/test/parsers/LineParser.ts
- src/test/parsers/LiteralArgumentParser.ts
- src/test/utils/NbtSchemaWalker.ts
- src/test/utils/StringReader.ts
- src/test/utils/utils.ts
- src/utils/NbtSchemaWalker.ts
- src/utils/StringReader.ts
- src/utils/utils.ts
> 💄 Update all quotes in messages

- README.md
- src/parsers/NbtTagArgumentParser.ts
- src/test/utils/NbtSchemaWalker.ts
- src/utils/NbtSchemaWalker.ts
> ♻️ Refactor NbtSchemaWalker

- src/test/utils/NbtSchemaWalker.ts
- src/utils/NbtSchemaWalker.ts
> ⚡️ Add cache in NbtSchemaWalker

- src/CommandTree.ts
- src/parsers/ArgumentParser.ts
- src/parsers/DefinitionDescriptionArgumentParser.ts
- src/parsers/DefinitionIDArgumentParser.ts
- src/parsers/LineParser.ts
- src/parsers/NbtTagArgumentParser.ts
- src/test/parsers/DefinitionDescriptionArgumentParser.ts
- src/test/parsers/DefinitionIDArgumentParser.ts
- src/test/parsers/NbtTagArgumentParser.ts
- src/types/GlobalCache.ts
- src/utils/NbtSchemaWalker.ts
> ♻️ Add new property 'cursor' to compute completions

- package-lock.json
- src/parsers/NbtTagArgumentParser.ts
- src/test/parsers/NbtTagArgumentParser.ts
- src/test/utils/NbtSchemaWalker.ts
- src/utils/NbtSchemaWalker.ts
> ✨ Finish all validations in NbtTagArgumentParser

- src/parsers/NbtTagArgumentParser.ts
- src/test/parsers/NbtTagArgumentParser.ts
> ♻️ Use the accurate article before tag names

- src/test/utils/utils.ts
- src/utils/utils.ts
> 🐛 Fix not quoting boolean-like strings

- README.md
- src/parsers/NbtTagArgumentParser.ts
- src/parsers/TagArgumentParser.ts
- src/test/parsers/LiteralArgumentParser.ts
- src/test/parsers/NbtTagArgumentParser.ts
- src/test/parsers/TagArgumentParser.ts
- src/test/types/Cache.ts
- src/test/utils/NbtSchemaWalker.ts
- src/types/Cache.ts
- src/types/Config.ts
- src/utils/NbtSchemaWalker.ts
> ✨ Finish TagArgumentParser

- src/types/Cache.ts
- src/types/NbtTag.ts
- src/utils/NbtSchemaWalker.ts
- src/utils/utils.ts
> 💄 Use Array#includes function

- src/parsers/ObjectiveArgumentParser.ts
- src/test/parsers/ObjectiveArgumentParser.ts
- src/types/Cache.ts
> ✨ Finish ObjectiveArgumentParser

- src/parsers/NumberRangeArgumentParser.ts
- src/test/parsers/NumberRangeArgumentParser.ts
- src/test/types/Cache.ts
- src/test/utils/StringReader.ts
- src/types/Entity.ts
- src/types/NumberRange.ts
- src/utils/StringReader.ts
> Add NumberRangeArgumentParser

- src/parsers/VectorArgumentParser.ts
- src/test/parsers/VectorArgumentParser.ts
- src/test/utils/StringReader.ts
- src/types/Vector.ts
- src/utils/StringReader.ts
> Add VectorArgumentParser

- package-lock.json
- package.json
- src/parsers/ItemSlotArgumentParser.ts
- src/parsers/LiteralArgumentParser.ts
- src/test/parsers/ItemSlotArgumentParser.ts
- src/typings/range.d.ts
- src/utils/StringReader.ts
> Add ItemSlotArgumentParser

- src/parsers/ScoreboardSlotArgumentParser.ts
- src/test/parsers/ScoreboardSlotArgumentParser.ts
> Add ScoreboardSlotArgumentParser

- src/parsers/LiteralArgumentParser.ts
- src/parsers/ObjectiveCriterionArgumentParser.ts
- src/parsers/ScoreboardSlotArgumentParser.ts
- src/test/parsers/LiteralArgumentParser.ts
- src/test/parsers/ObjectiveCriterionArgumentParser.ts
- src/test/parsers/ScoreboardSlotArgumentParser.ts
- src/utils/StringReader.ts
> Add ObjectiveCriterionArgumentParser

- src/parsers/ItemArgumentParser.ts
- src/test/parsers/BlockArgumentParser.spec.ts
- src/test/parsers/ItemArgumentParser.spec.ts
- src/test/types/Item.spec.ts
- src/types/Item.ts
> Add ItemArgumentParser

- src/parsers/MessageArgumentParser.ts
- src/test/parsers/MessageArgumentParser.spec.ts
> Add MessageArgumentParser

- src/client.ts
- src/server.ts
> Move cache mechanism to client

- src/server.ts
- src/types/ClientCache.ts
> Support document links

- README.md
- src/parsers/ArgumentParserManager.ts
- src/parsers/EntityArgumentParser.ts
- src/parsers/LiteralArgumentParser.ts
- src/parsers/QuotableLiteralArgumentParser.ts
- src/server.ts
- src/test/parsers/LiteralArgumentParser.spec.ts
- src/test/parsers/QuotableLiteralArgumentParser.spec.ts
- src/types/Config.ts
- src/utils/StringReader.ts
> Fix not supporting quotes in entity selectors

- README.md
- language-configuration.json
- src/CommandTree.ts
- src/data/vanilla_nbt_schema.ts
- src/parsers/LineParser.ts
- src/parsers/NbtPathArgumentParser.ts
- src/parsers/NbtTagArgumentParser.ts
- src/parsers/TextComponentArgumentParser.ts
- src/test/CommandTree.spec.ts
- src/test/types/Entity.spec.ts
- src/test/types/NbtTag.spec.ts
- src/test/utils/NbtSchemaWalker.spec.ts
- src/test/utils/StringReader.spec.ts
- src/types/Identity.ts
- src/types/NbtTag.ts
- src/utils/NbtSchemaWalker.ts
- src/utils/StringReader.ts
> Release v1.8.2

- src/server.ts
> Release 1.9.0

- .all-contributorsrc
- README.md
- src/CommandTree.ts
- src/data/vanilla_nbt_schema.ts
- src/parsers/BlockArgumentParser.ts
- src/parsers/TextComponentArgumentParser.ts
- src/test/parsers/BlockArgumentParser.spec.ts
> Release 1.9.4

- src/CommandTree.ts
- src/client.ts
- src/parsers/NamespacedIDArgumentParser.ts
- src/server.ts
- src/test/types/ClientCache.spec.ts
- src/test/types/Identity.spec.ts
- src/types/ClientCache.ts
- src/types/Identity.ts
- src/types/Line.ts
- src/types/Parser.ts
> Release 1.10.4

- src/CommandTree.ts
- src/types/CommandTree.ts
> Fix the completions for non-definition comments

- .gitignore
- .npmignore
- .vscode/launch.json
- .vscodeignore
- README.md
- package-lock.json
- package.json
- src/client.ts
- src/data/BlockDefinition.ts
- src/types/ParsingContext.ts
- tsconfig.json
- webpack.config.js
> Bundle dist codes

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- README.md
- src/client.ts
- src/server.ts
> Move cache files to VSCode's storagePath

- contributors/.all-contributorsrc
- contributors/2.1.0.md
- src/data/CommandTree1.15.ts
- src/data/CommandTree1.16.ts
> Fix worldborder add showing an error for negative values

- src/CommandTree.ts
- src/data/VanillaData.ts
- src/parsers/EntityArgumentParser.ts
> Fix not completing NBT for certain selectors

- src/CommandTree.ts
- src/data/CommandTree1.15.ts
- src/data/CommandTree1.16.ts
- src/locales/index.ts
- src/parsers/EntityArgumentParser.ts
- src/server.ts
- src/test/CommandTree.spec.ts
- src/test/parsers/EntityArgumentParser.spec.ts
- src/test/utils/handlers/common.spec.ts
- src/utils/handlers/index.ts
- src/utils/handlers/onRenameRequest.ts
> Only get data, tree, and config when necessary

- README.md
- contributors/.all-contributorsrc
- contributors/2.1.0.md
- src/utils/NbtdocHelper.ts
Fields with 0-length Or will never be merged in. Conflicted fields will be merged in to an Or doc.
> 🐛 Fix merging tags when compile fallback docs

- src/nodes/VectorNode.ts
- src/parsers/VectorArgumentParser.ts
- src/test/CommandTree.spec.ts
- src/test/nodes/VectorNode.spec.ts
- src/test/parsers/VectorArgumentParser.spec.ts
> :bug: Fix align code action when not allowed float

- src/data/CommandTree1.15.ts
- src/data/CommandTree1.16.ts
- src/parsers/VectorArgumentParser.ts
- src/test/parsers/VectorArgumentParser.spec.ts
> :bug: Fix missing spawnpoint angle arguments

- src/test/types/NamingConventionConfig.spec.ts
- src/types/NamingConventionConfig.ts
> :bug: Fix require sep and parts in convention config

- src/parsers/EntityArgumentParser.ts
> :bug: Fix throw lint errors score_holder-wildcards

- packages/datapack-language-server/src/parsers/ObjectiveArgumentParser.ts
- packages/datapack-language-server/src/parsers/TeamArgumentParser.ts
- packages/datapack-language-server/src/test/parsers/ObjectiveArgumentParser.spec.ts
- packages/datapack-language-server/src/test/parsers/TeamArgumentParser.spec.ts
> :bug: Fix wrong diagnostic severity

- packages/vscode-extension/.vscodeignore
More info: https://github.com/microsoft/vscode-vsce/issues/588
> ⏪️ Revert .vscodeignore changes

- .packages.json
- package-lock.json
- packages/mcdoc-cli/.npmignore
- packages/mcdoc-cli/README.md
- packages/mcdoc-cli/package.json
- packages/mcdoc-cli/src/index.ts
- packages/mcdoc-cli/src/tsconfig.json
- packages/mcdoc-cli/test/tsconfig.json
- packages/mcdoc-cli/tsconfig.json
- packages/tsconfig.json
> ✨ Mcdoc cli

- src/data/CommandTree1.19.4.ts
How come no one noticed (even though roughly four people were checking
Fix #1021
> :bug: Fix incorrect AST for `/damage`

- src/locales/en.json
- src/locales/ja.json
No one noticed ¯\\\_(ツ)\_/¯
Forgotten items in #716
> :bug: Fix unknown locale key: `argument-type.vector.1D`

- src/plugins/builtin/McfunctionPlugin.ts
> :bug: Fix macro indentation not being taken into account

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftEntity.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftGameProfile.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftGamemode.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftMessage.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftScoreHolder.spec.js
- packages/java-edition/src/mcfunction/common/index.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
the build on `main` has a failing test because we didn't commit the new snapshot result after running `npm test` in https://github.com/SpyglassMC/Spyglass/pull/1075 (cc @NeunEinser )
(we also apparently didn't run the formatter on the changed files)
~~it seems like we don't have GitHub Actions enabled to run on forks? we should probably change that so we can ensure the build is passing before we merge PRs from forks (which AFAIK all new v4 contributors can only push to forks)~~
actually i _am_ seeing builds run on https://github.com/SpyglassMC/Spyglass/pull/1075 's fork, we just merged it without checking for a passing build 😖 
--- 
i think we should enable `Require status checks to pass before merging` to avoid this in the future
> 📸 Update snapshots to include gamemode parser

- packages/locales/src/index.ts
- packages/locales/test/index.spec.ts
> 🐛 Fix how locales with subtags are handled

- docs/user/mcdoc/index.adoc
- packages/mcdoc/src/node/index.ts
- packages/mcdoc/src/parser/index.ts
> 🐛 Fix doc comments

- packages/playground/esbuild.js
- packages/vscode-extension/esbuild.mjs
Fixes #1143
~~(Pending verification by the Issue author)~~
Verified by Nicoder internally.
> 🔨 Fix building issues on MacOS

- .dprint.jsonc
- package-lock.json
- package.json
- packages/java-edition/src/mcfunction/tree/patch.ts
- packages/mcfunction/src/completer/index.ts
> ⬆️ Upgrade dprint

- packages/vscode-extension/.vscodeignore
- packages/vscode-extension/src/extension.mts
> 🧑‍💻 Enable source maps in stack traces

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftEntity.spec.js
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
- packages/locales/src/locales/en.json
Basic support and unit tests for the new `@n` entity selector!
Closes #1204
> ✨ Add support for @n

- __snapshots__/packages/mcdoc/test-out/runtime/checker.spec.js
- packages/mcdoc/test/runtime/checker.spec.ts
> ✅ Add mcdoc runtime tests

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftStyle.spec.js
- packages/java-edition/src/mcfunction/checker/index.ts
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
> ✨ Add style parser and validate with mcdoc

- __snapshots__/packages/mcdoc/test-out/runtime/checker.spec.js
- packages/locales/src/locales/en.json
- packages/mcdoc/src/runtime/checker/index.ts
- packages/mcdoc/test/runtime/checker.spec.ts
> 🐛 Implement mcdoc string length check

- .eslintrc.cjs
- packages/core/src/processor/binder/builtin.ts
- packages/core/src/service/Downloader.ts
- packages/core/src/symbol/SymbolUtil.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/json/src/completer/index.ts
- packages/json/src/parser/number.ts
- packages/language-server/src/server.ts
- packages/language-server/src/util/toLS.ts
- packages/mcdoc/src/runtime/checker/index.ts
- packages/mcdoc/test/runtime/checker.spec.ts
- packages/nbt/src/checker/index.ts
- packages/nbt/src/completer/index.ts
see: [`object-shorthand`](https://eslint.org/docs/latest/rules/object-shorthand)
split from https://github.com/SpyglassMC/Spyglass/pull/1250
---
also see brief discussion on [discord](https://discord.com/channels/666020457568403505/666037123450929163/1249486596286189690)
> 🎨 Enable `object-shorthand` lint rule

- packages/mcdoc/src/runtime/checker/index.ts
- packages/mcdoc/src/runtime/completer/index.ts
> 🐛 Attach all validDefinitions to nodes

- __snapshots__/packages/core/test-out/parser/list.spec.js
- __snapshots__/packages/core/test-out/parser/record.spec.js
- __snapshots__/packages/core/test-out/parser/string.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/brigadierString.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftComponent.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftEntity.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftLootModifier.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftLootPredicate.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftNbtTag.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftParticle.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftStyle.spec.js
- __snapshots__/packages/json/test-out/parser/array.spec.js
- __snapshots__/packages/json/test-out/parser/object.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/attributed_types.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/dispatcher/random_number_generator.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/enum/string.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/simple_types.spec.js
- __snapshots__/packages/mcdoc/test-out/parser/syntax/type/literalType.spec.js
- __snapshots__/packages/mcdoc/test-out/parser/terminator/string.spec.js
- __snapshots__/packages/nbt/test-out/parser/collection.spec.js
- __snapshots__/packages/nbt/test-out/parser/path.spec.js
- __snapshots__/packages/nbt/test-out/parser/primitive.spec.js
- packages/core/src/node/StringNode.ts
- packages/core/src/parser/string.ts
- packages/core/src/processor/completer/builtin.ts
- packages/json/src/completer/index.ts
- packages/nbt/src/completer/index.ts
- Fixes #1284 
I don't like the implementation of this yet, so this may need to be improved. Ideally they'd also share the implementation of the core string completer (which has a TODO for this issue)
> 🐛 Escape completions in string

- packages/core/src/service/CacheService.ts
- for https://github.com/SpyglassMC/Spyglass/pull/1290
- didn't know this version was a thing in that PR
> 🔖 Bump cache version for mcdoc doc comments hover

- package-lock.json
- packages/json/src/completer/index.ts
- packages/mcdoc/src/runtime/checker/index.ts
- packages/mcdoc/src/runtime/completer/index.ts
- packages/nbt/src/completer/index.ts
Fixes #1263
Auto complete does not appear to work for this kind of key yet.
> 🐛 Fix type info not being attached to keys by mcdoc runtime

- packages/nbt/src/parser/collection.ts
- packages/nbt/src/parser/compound.ts
> 🐛 Allow trailing commas in SNBT

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftItemPredicate.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftItemStack.spec.js
- packages/java-edition/src/mcfunction/checker/index.ts
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
I caused this in #1302, it's only fair that I fix it again
- Fixes #1331
> 🐛 Make component tests between brackets optional

- __snapshots__/packages/core/test-out/source/Source.spec.js
- packages/core/src/source/Source.ts
- packages/core/test/source/Source.spec.ts
this was helping so far in troubleshooting #1296. specifically in figuring out what point the index map was being messed up.
see snapshots
---
sample use with console.logs:
> ✨ Add debug method to `Source` for better `IndexMap` visualization

- packages/java-edition/src/mcfunction/parser/argument.ts
> :bug: Fix selector parser being too strict in /say

- packages/java-edition/src/mcfunction/checker/index.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/src/mcfunction/tree/patch.ts
- packages/nbt/src/checker/index.ts
> 🐛 Allow missing keys in data merge command

- packages/core/src/processor/completer/builtin.ts
- packages/json/src/completer/index.ts
- packages/mcdoc/src/runtime/completer/index.ts
- packages/nbt/src/completer/index.ts
> ✨ Add THIS completion item

- packages/java-edition/src/mcfunction/checker/index.ts
> 🐛 Fix selector nbt argument

- packages/core/src/symbol/Symbol.ts
> ✨ Add attribute modifier symbol

- packages/java-edition/src/mcfunction/tree/patch.ts
I just realized I forgot insert in #1405
> Fix insert not using list item

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftScoreboardSlot.spec.js
- packages/java-edition/src/mcfunction/common/index.ts
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
> 🐛 Update below_name scoreboard slot

- packages/core/src/processor/completer/builtin.ts
- packages/core/src/service/Config.ts
- packages/java-edition/src/mcfunction/mcdocAttributes.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/src/mcfunction/tree/patch.ts
> ✨ Enter score holders, tags, and storages as definition in some usages

- packages/mcdoc/src/runtime/attribute/builtin.ts
This adds autocomplete for `custom_data` and marker `data`
> ✨ Implement dispatcher_key attribute

- .github/workflows/release.yml
- package-lock.json
- packages/vscode-extension/package.json
Very much untested, taken mostly from <https://github.com/SpyglassMC/vscode-datapack/blob/legacy-v3/.github/workflows/release.yml>
> 🔧 Add publish vscode extension step to release workflow

- packages/core/src/processor/completer/Completer.ts
- packages/java-edition/src/index.ts
- packages/json/src/checker/index.ts
- packages/json/src/completer/index.ts
- packages/language-server/src/util/toLS.ts
- packages/locales/src/locales/en.json
- packages/mcdoc/src/runtime/attribute/index.ts
- packages/mcdoc/src/runtime/checker/context.ts
- packages/mcdoc/src/runtime/checker/index.ts
- packages/mcdoc/src/runtime/completer/index.ts
- packages/nbt/src/checker/index.ts
- packages/nbt/src/completer/index.ts
> ✨ Add pack format mcdoc attribute

- packages/language-server/src/server.ts
- packages/locales/src/locales/en.json
- packages/vscode-extension/src/extension.mts
> ✨ Add progress indicator on initialization

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftEntity.spec.js
- packages/core/src/node/SymbolNode.ts
- packages/core/src/processor/binder/builtin.ts
- packages/java-edition/src/json/index.ts
- packages/java-edition/src/json/mcdocAttributes.ts
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/src/mcfunction/tree/patch.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
- packages/mcfunction/src/completer/index.ts
- packages/mcfunction/src/parser/argument.ts
- packages/mcfunction/src/parser/command.ts
> ✨ Add advancement criterion checking and suggestions

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftObjectiveCriteria.spec.js
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
> 🐛 Add teamkill and killedByTeam scoreboard criteria

- packages/java-edition/src/mcfunction/mcdocAttributes.ts
Accompanied by https://github.com/SpyglassMC/vanilla-mcdoc/commit/1a6f538b663b1e3540dc5b55bd791cfbb99f4d36
> 🐛 Add block_predicate attribute

- packages/core/src/parser/util.ts
- packages/core/src/processor/binder/builtin.ts
- packages/core/src/processor/checker/builtin.ts
- packages/core/src/service/Context.ts
- packages/core/src/service/ErrorReporter.ts
- packages/core/src/service/Project.ts
- packages/core/src/source/LanguageError.ts
- packages/java-edition/src/index.ts
- packages/language-server/src/util/toLS.ts
This turned out to be surprisingly simple to add. Will help users and us when troubleshooting errors.
> ✨ Add loaded version to diagnostic source

- packages/language-server/src/server.ts
- packages/language-server/src/util/types.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/extension.mts
- Restart/notify the language server when the setting changes
> ✨ Add gameVersion to vscode settings

- docs/user/commands.adoc
- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/extension.mts
Because it is annoying to tell people how to find the output logs
> ✨ Add "Show Output" command

- packages/nbt/src/checker/index.ts
> 🐛 Remove collection length errors in nbt predicates

- packages/core/src/common/externals/NodeJsExternals.ts
It turned out to be a really simple fix (excluding the work in #1599)
Fixes #1601
> 🐛 Disable chokidar globbing

- __snapshots__/packages/java-edition/test-out/dependency/mcmeta.spec.js
- packages/java-edition/src/dependency/mcmeta.ts
> ✨ Implement mcdoc:block_states and mcdoc:block_state_keys

- packages/java-edition/src/mcfunction/parser/argument.ts
> 🐛 Fix item predicate parser not accepting some whitespace

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftScoreHolder.spec.js
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
> 🐛 Parse * wildcard score holder separately from fake players

- packages/core/src/service/Config.ts
- packages/java-edition/src/mcfunction/mcdocAttributes.ts
- packages/java-edition/src/mcfunction/tree/patch.ts
> 🐛 Always delcare tag symbols as references

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftItemStack.spec.js
- packages/java-edition/src/mcfunction/checker/index.ts
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
> ✨ Support component removal

- packages/core/src/symbol/Symbol.ts
- packages/java-edition/src/json/completer/index.ts
- packages/java-edition/src/json/index.ts
- packages/java-edition/src/json/mcdocAttributes.ts
- packages/java-edition/src/json/node/index.ts
- packages/java-edition/src/json/parser/index.ts
> ✨ Properly support texture references in models

- packages/core/src/symbol/Symbol.ts
- packages/java-edition/src/binder/index.ts
- packages/java-edition/src/json/checker/index.ts
- packages/vscode-extension/src/extension.mts
* `sounds.json`
* `gpu_warnlist.json`
* `regional_compliancies.json`
* `lang/deprecated.json`
* `textures/**/*.png.mcmeta`
> ✨ Support special resource pack files

- packages/core/src/processor/completer/Completer.ts
- packages/core/src/processor/completer/builtin.ts
- Fixes #1518
Not really a nice fix, but I think it works
> 🐛 Fix double-escaping completion items in strings

- packages/mcdoc/src/binder/index.ts
- Introduced in #1673
- Fixes #1679
> 🐛 Fix hoisted mcdoc types losing their attributes

- packages/language-server/src/util/toLS.ts
> 🐛 Fix documentSymbol request errors

- __snapshots__/packages/java-edition/test-out/json/parser/index.spec.js
- packages/java-edition/src/json/parser/index.ts
- packages/java-edition/test/json/parser/index.spec.ts
- packages/locales/src/locales/en.json
- packages/vscode-extension/package.json
> 💬 Add hint for escaping percent signs

- .gitignore
- packages/language-server/src/server.ts
> Do not send documents for archive urls (Fixes #1745)

- package-lock.json
- packages/web-api-server/package.json
- packages/web-api-server/src/index.ts
Fix #1734
Cherry picked from #1746 for deployment soon as it's a simple fix while #1746 has the potential to break things.
> 🐛 Lock when updating git repos

- packages/java-edition/src/mcfunction/mcdocAttributes.ts
> ✨ Filter out errors of incomplete suggest commands

- packages/mcdoc/src/runtime/completer/index.ts
> 🐛 Fix completions of enum keys

- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
> ✨ Support resource_selector argument parser

- packages/locales/src/locales/en.json
- packages/mcdoc/src/runtime/attribute/builtin.ts
> ✨ Implement divisible_by mcdoc attribute

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftDialog.spec.js
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
> ✨ Implement `dialog` command parser

- CONTRIBUTING.md
- README.md
> 📝 Update contributing.md
