- .gitattributes
This PR attempts to cleanup the diffs on this repo. This is best illustrated with the following image from a recent commit (fec3da0d20d17e1ecae6d7c8547b0c13970a06d3). Only the blue part is relevant code changes. Note that you will still be able to view the diffs for these contributor files. [More info](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-how-changed-files-appear-on-github).
> Mark readme and contributing as generated files

- package.json
- src/locales/index.ts
- src/utils/JsonSchemaHelper.ts
Required changes for to be able to upgrade `@mcschema/core` to `0.11.0`.
The language server now needs to handle localization itself since it has been removed from @mcschema/core. But since it already had localization I decided to simply merge the objects. *I assume there are no conflicting translation keys?*
This also adds a `segmentedLocale` exported function in `locales/index.ts`. This is the equivalent of `Path.strictLocale`.
> Update json localization

- packages/datapack-language-server/src/parsers/NbtPathArgumentParser.ts
> :bug: NBTPath doesn't throw an error on consecutive "."

- src/data/CommandTree1.17.ts
- src/locales/en.json
- src/locales/ja.json
- src/locales/zh-cn.json
- src/locales/zh-tw.json
- src/services/onCodeAction.ts
Also updates the existing code action.
Does *not* add a new code action to convert from the old /item syntax.
> Update item syntax to 21w19a

- package-lock.json
- package.json
- src/data/CommandTree1.19.4.ts
- src/data/JsonSchema.ts
- src/types/ClientCache.ts
- src/utils/PathPatterns.ts
Accompanying `damage_type` and `tags/damage_type` support has also been added.
> :sparkles: Support new `/damage` commands

- docs/user/mcdoc/index.adoc
I was implementing a parser and noticed that some of the examples were invalid
> Small fixes in mcdoc examples

- packages/mcfunction/src/colorizer/index.ts
- packages/mcfunction/src/completer/index.ts
- packages/mcfunction/src/node/command.ts
- packages/mcfunction/src/node/entry.ts
- packages/mcfunction/src/parser/entry.ts
Simply removes the parse error and adds a simple string colorizer for macro lines
> ✨ Add simple macro parser and colorizer

- packages/tsconfig-base.json
Bundler coming in clutch instead of Node16 which made the TS compiler want to use Node16
> :hammer:  Resolve moduleResolution version issues with "Bundler"

- packages/playground/esbuild.js
- packages/playground/package.json
- packages/vscode-extension/esbuild.mjs
- packages/vscode-extension/package.json
This PR re-enables debugging through VSCode's builtin debugger with **breakpoints**
**before**: setting a breakpoint in a `.ts` file wouldn't actually bind and the language server would not hit it
**after**: setting a breakpoint catches successfully and pauses the server when it is hit
|before|
|-|
| ![image](https://github.com/SpyglassMC/Spyglass/assets/13565346/15051881-e671-4187-889d-7179e7e1b3e9) |
|after|
| ![image](https://github.com/SpyglassMC/Spyglass/assets/13565346/cb0b2295-e96e-4689-963f-77ef6fc37062) |
since `packages/vscode-extension`'s `watch` script was calling `npm run build` (instead of `npm run build:dev`), it was calling `esbuild.mjs` with the `prod` arg (instead of `dev`).
https://github.com/SpyglassMC/Spyglass/blob/3f4cc126ab8f096988b45aed2904dca024f08bab/packages/vsco …
> 🔨 Fix debug breakpoints not binding

- README.md
- packages/core/src/source/IndexMap.ts
- packages/core/src/source/Source.ts
- packages/core/test/source/IndexMap.spec.ts
- packages/core/test/source/Range.spec.ts
- packages/core/test/source/Source.spec.ts
ran into this while working on #1069 
we were lacking in unit test coverage when it came to how `IndexMap`s interact with `Source`s, so the first commit adds some to make this error stand out more obviously: [`24c5607` (#1124)](https://github.com/SpyglassMC/Spyglass/pull/1124/commits/24c5607ee3cc6c9117ac80e7edc79230512be0b4)
see the following example (same as the new unit tests):
```ts
/*
* Index Tens - 000000000011111111112
* Index Ones - 012345678901234567890
* Outer      - foo\"bar\u00a7qux
* Inner      - foo"bar§qux
*/
const indexMap = [
// `"` to `\"`
{ inner: Range.create(3, 4), outer: Range.create(3, 5) },
// `§` to `\u00a7`
{ inner: Range.create(7, 8), outer: Range.create(8, 14) },
]
```
trying to fetch the **outer** range of `r` in the above case _should_ output `[7, 8)` (`r` is …
> 🐛 Fix `IndexMap`'s `toInnerRange` and `toOuterRange` returning extended ranges

- package-lock.json
- packages/core/package.json
- packages/core/src/common/externals/NodeJsExternals.ts
- packages/core/src/common/externals/index.ts
- packages/core/src/common/util.ts
- packages/core/src/service/Config.ts
- packages/core/src/service/FileService.ts
- packages/core/src/service/Project.ts
- packages/core/src/service/fileUtil.ts
- packages/java-edition/src/dependency/index.ts
- packages/java-edition/src/index.ts
- packages/language-server/src/server.ts
- packages/vscode-extension/package.json
* Changed archive URI format to `archive://<archive_name>/<path_to_file>`
* Use `URL` class from `whatwg-url` package instead of the built-in one for issues encountered in the browser (7fd01cac51c59616c6c422bb7e967ac195e9568d)
* Added a dependency provider `@vanilla-datapack`. All symbols from the vanilla datapack will be loaded in the project symbol table and go to definition will work on the vanilla symbols properly.
https://github.com/SpyglassMC/Spyglass/assets/15277496/5994c628-3b0c-452f-ad81-0c82329f44a0
> Add vanilla datapack dependency

- .vscode/snippets.code-snippets
- packages/core/src/common/Dev.ts
- packages/core/src/common/ReadonlyProxy.ts
- packages/core/src/common/StateProxy.ts
- packages/core/src/common/externals/downloader.ts
- packages/core/src/common/util.ts
- packages/core/src/node/CommentNode.ts
- packages/core/src/processor/binder/Binder.ts
- packages/core/src/source/LanguageError.ts
- packages/core/test/common/util.spec.ts
- packages/core/test/utils.ts
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/mcdoc/src/binder/index.ts
- packages/mcdoc/src/node/index.ts
- packages/mcfunction/src/node/command.ts
Renamed the utility type `NodeIsHelper` to ~~`PotentiallyReadonly`~~ `InheritReadonly` and improved documentation and tests.
> Improve AST node type guards

- .vscode/launch.json
- .vscode/tasks.json
- package-lock.json
- packages/core/src/processor/InlayHintProvider.ts
- packages/core/src/service/Config.ts
- packages/java-edition/src/mcfunction/inlayHintProvider.ts
- packages/language-server/package.json
- packages/language-server/src/server.ts
- packages/language-server/src/util/toLS.ts
- packages/language-server/src/util/types.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.mts
Resolves #1137.
* Updates dependencies on `vscode-languageserver` and `vscode-languageclient`.
* Uses LSP to provide inlay hints instead of our own protocol.
* Enables inlay hints on more command nodes by default:
* 'boolean',
* 'double',
* 'float',
* 'integer',
* 'long',
* 'mcfunction:coordinate',
* 'mcfunction:vector',
* 'mcfunction:command_child/unknown'
* The rationale behind these nodes is that they're fairly "simple" (subjectively) that it may not be immediately clear to an inexperienced command user what the argument is for. e.g. the boolean argument in `effect give`, the various vectors in `clone`, `tp`, etc, while a more "complicated" node like a block ID is more obvious that it represents a type of block.
> ♻️ Use LSP to provide inlay hints

- packages/java-edition/src/dependency/common.ts
- packages/java-edition/src/dependency/mcmeta.ts
Instead of using a map of regexes to convert the pack format to a release version, it loops over all versions to find the correct release version.
- If the pack format is higher than the latest release, use the latest snapshot
- Look for versions from recent to oldest, picking the most recent release that matches
- If the pack format is still lower than the oldest version, simply use the oldest release (which is 1.14)
Additionally, this PR fixes the issue when the `release_target` field is missing in versions after 22w42a
- If the version is already a release, us its own `id` field
- It tries to find the next release cronologically
- If there is no release, hardcode the current release target (this may be improved in the future)
> 🐛 Improve version and release target resolution

- __snapshots__/packages/nbt/test-out/parser/path.spec.js
- packages/nbt/src/parser/path.ts
Fixes #1058. This change allows single quotes for
all versions, not just the versions after 1.20 Pre- release 2, as the `nbt` package does not have
access to the `ReleaseVersion.cmp()` function from `java-edition` and it'd take too much effort to
do it properly just to eliminate a tiny little
false negative. We may revisit this if we decide
to use pack formats internally instead since it'd
be an easy
`parseInt(ctx.project['loadedFormat']) < 15` check.
> 🐛 Allow single quotes in NBT paths

- .gitattributes
- .vscode/launch.json
- README.md
useful when you're trying to test some functionality and are able to mock your context within a unit test.
nice to not have to run the entire extension window when a feature is earlier in development
sample:
> 🔧 Add launch configuration to run tests with VSCode debugger

- .vscode/launch.json
- when you're debugging these, it's not unlikely you'd be in a test longer than 30s (the default timeout)
- new default is 999999s (11.5 days)
---
- split from https://github.com/SpyglassMC/Spyglass/pull/1180
> 🔧 Add long timeout arg to unit test launch configuration

- __snapshots__/packages/mcdoc/test-out/__fixture__/attributed_types.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/dispatcher/random_number_generator.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/struct/nested_spread.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/struct/simple.spec.js
- __snapshots__/packages/mcdoc/test-out/__fixture__/type_alias/attributed.spec.js
- packages/java-edition/src/json/checker/index.ts
- packages/mcdoc/src/binder/index.ts
- packages/mcdoc/src/type/index.ts
- packages/mcdoc/test/__fixture__.mcdoc
- packages/nbt/src/checker/index.ts
The attributed type contained a single attribute with another child, which itself could be an attributed type for multiple attributes on a single type.
This can be quite annoying to deal with, especially when different processes still need to be able to access attributes, but also you want to check whether a type node is of a certain type.
With the old concept, you'd need to essentially recurse into the type tree for as long as the current node is still an attributed type.
With this, all types can simply have attributes and they can be dealt with when appropriate.
This is also more consistent with `StructTypeField` and `EnumTypeField`.
> 🔧 Remove attributed type in favor of attributes array on all types

- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
Closes #1163
I looked at the tests for a bit but I didn't see a good way to test these parsers in multiple versions. Right now `mockProjectData` is hardcoded to 1.15. This might be something to do in a later PR.
> ✨ Add support for new particle format

- packages/core/src/processor/completer/builtin.ts
- packages/core/src/processor/linter/builtin/undeclaredSymbol.ts
Fixes #1220 
Also improves the resource location completer so it no longer suggests the current or other undeclared symbols.
|Before|After|
|---|---|
|![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/05880d83-2324-4333-9ce6-ed9feb117e14)|![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/42ac376a-7a6b-462d-8759-bfdac05994ed)|
> 🐛 Re-enable undeclared symbols linter

- packages/core/src/symbol/Symbol.ts
- packages/java-edition/src/dependency/common.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/src/mcfunction/tree/patch.ts
Resolves #1113.
- #1191
- #1192
> 🦺 Validate command tree patch

- .github/workflows/commit.yml
This allows us to have useful testing for WIP PRs that don't necessarily follow the linting rules.
> ♻️ Move formatter check to `Lint` job

- __snapshots__/packages/language-server/test-out/util/toLS.spec.js
- packages/language-server/src/util/toLS.ts
- packages/language-server/test/util/toLS.spec.ts
I'll have some upcoming PRs relating to fixing the colorizer across multiple lines (due to backslash continuation)
I wanted to add tests for this, but it wouldn't be great with snapshots since the return type of `semanticTokens()` is just an array of integers (kinda meaningless to the human eye)
https://github.com/SpyglassMC/Spyglass/blob/9bb9dc1bb0c70f178a6b5efac20816346411d621/packages/language-server/src/util/toLS.ts#L321-L325
---
@SPGoding do you remember what file type you were using to colorize tokens across multiple lines prior to backslash continuation?
- relevant commit is from 2 years ago: https://github.com/SpyglassMC/Spyglass/commit/e15cf81ec9060f2b7d9055a0faa4c67fba736fd1
---
|| before | after |
|-|-|-|
| commands w/line continuation | …
> 🐛 Fix semantic token builder not coloring each line of a color token

- __snapshots__/packages/mcdoc/test-out/runtime/checker.spec.js
- packages/mcdoc/src/runtime/checker/index.ts
- packages/mcdoc/test/runtime/checker.spec.ts
Replaces the old `O(n^2)` field de-duplication check in the struct simplify case. Now a map of fields is used for literal keys, and only the complex keys are checks if they are assignable.
> ⚡️ Optimize struct field duplicate filtering

- packages/mcdoc/src/runtime/attribute/index.ts
- packages/mcdoc/src/runtime/checker/index.ts
The vast majority (if not all) calls to `isAssignable` compare two literal types. This PR introduces a fast path for those cases, assuming that two literal types of the same kind are always equal to each other when their values match.
A few benchmarks:
* 9.39ms -> 2.36ms
* 170.11ms -> 117.26ms
* 320.82ms -> 274.17ms
That last one in particular was
```
data merge entity @s {Air:1b,state:"rolling",Passengers:[{Air:0}]}
```
Additionally this PR removes some of the attribute warnings, bringing the total time of that last example all the way down to 8.08ms!
> ⚡ Optimize `isAssignable` for literal types

- packages/core/src/service/Downloader.ts
- packages/java-edition/src/dependency/index.ts
- Fixes #1258
The issue was caused because the `vanilla-datapack` and `vanilla-mcdoc` dependencies relied on the downloader setting the `out.cacheUri` field. This did not happen when memory cache was found (because only the raw buffer was stored in the memory cache).
The memory cache is only intended to last 15 seconds, but due to a logic error, memory cache entries never expired.
> 🐛 Fix `Reset Project Cache` command

- packages/json/src/checker/index.ts
- packages/mcdoc/src/binder/index.ts
- packages/mcdoc/src/node/index.ts
- packages/mcdoc/src/runtime/checker/index.ts
- packages/mcdoc/src/type/index.ts
- packages/nbt/src/checker/index.ts
- Fixes #1264 
**Important:**
When switching to this PR, run `Reset Project Cache` to allow the doc comments to be included in the symbol table
> ✨ Show doc comments on mcdoc hover

- packages/nbt/src/checker/index.ts
- Fix #1274 
Future work should allow `isEquivalent` to check the value of a literal
> 🐛 Allow nbt byte to be assignable to boolean

- packages/json/src/completer/index.ts
- packages/nbt/src/completer/index.ts
When the completer cursor is not inside the string node, don't try to get the completions from it, instead fall back to the `getValues` call, which corrects the range to the current cursor.
This didn't seem to be needed for nbt, but I added it anyways to keep the code consistent. It seems like the real issue is caused by the JSON parser, adding an empty `json:string` node for pairs. This should be corrected in the future. But even with that fix, it doesn't hurt to have this check.
> 🐛 Fix completer issue when cursor is not inside string node

- packages/java-edition/src/mcfunction/checker/index.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/src/mcfunction/tree/patch.ts
- packages/nbt/src/checker/index.ts
I realized this only now. We should use `minecraft:block` when we are dispatching block IDs. The `minecraft:block_entity` dispatcher is mostly used internally to map from a block to a block entity.
This fixes a command like `setblock ~ ~ ~ chest{Items:[]}` where previously on hover it would show all possible Items fields (fallback case).
> 🐛 Use minecraft:block dispatcher instead of minecraft:block_entity

- packages/mcdoc/src/runtime/checker/index.ts
Only pair fields were getting filtered by attributes like `since` and `until`. Moving the logic to an earlier place.
> 🐛 Fix: also filter spread fields

- packages/vscode-extension/src/extension.mts
- Fixes #1307 
This does not add support for setting the language to jsonc, but it makes sure that the language server won't crash.
> 🐛 Fix crash when setting language to jsonc

- packages/core/src/common/externals/NodeJsExternals.ts
The `globby` expects only `/`, but `toPath` returned `\` on windows. Implementation is a bit rough, there may be other uses of `toPath` that need this treatment.
> 🐛 Fix getAllFiles nodejs implementation on windows

- packages/java-edition/src/mcfunction/tree/patch.ts
The game uses a greedy string to parse this argument, with a custom suggest method that lists all the currently scheduled functions. We need to patch this to just show all functions.
> 🐛 Add patch for schedule clear command

- packages/core/src/symbol/SymbolUtil.ts
- Fixes #1327 
The `SymbolUtil#clear` function takes a `contributor`, but the bug was that it only used this contributor for getting the right symbol cache. When actually removing the symbol locations it removes all of the locations. This breaks when there is a symbol reference (contributed by `binder`) in the same file that defines it (contributed by `uri_binder`).
> 🐛 Fix symbol clear not checking contributor when removing locations

- .github/workflows/commit.yml
- .github/workflows/release.yml
- README.md
- packages/core/test/source/Source.spec.ts
we can pass in `--forbid-only` to mocha to automatically ensure we aren't pushing `.only` to Github
---
> 🔧 Make build fail if a `.only` test is pushed

- packages/mcdoc/src/runtime/attribute/index.ts
- packages/mcdoc/src/runtime/completer/index.ts
This is an ugly fix. Ideally it should run the simplifier, but that would require some more substantial refactors.
- Fixes #1349
> 🐛 Fix enum filtering in completer

- packages/core/src/symbol/Symbol.ts
- packages/java-edition/src/binder/index.ts
- packages/vscode-extension/package.json
Enchantment providers were missing from the binder.
> 🐛 Bind enchantment provider

- packages/core/src/common/externals/BrowserExternals.ts
- packages/core/src/common/externals/NodeJsExternals.ts
- packages/core/src/common/externals/index.ts
- packages/core/src/service/CacheService.ts
- packages/core/src/service/FileService.ts
Cached files in an archive were getting detected as "changed" rather than "removed". The issue was that the cache service relied on detecting `ENOENT` and `EISDIR` codes in the thrown error, but this only happened for actual files on the file system, not for files in an archive.
Importantly, this does **not** solve #1213, I haven't been able to reproduce that error (which is slighly different).
> 🐛 Fix cached files in archives not detected as removed

- packages/java-edition/src/mcfunction/node/argument.ts
This particle type was added in 24w13a (1.20.5 snapshot), and since it has a required `block_state` option, we need to manually specify it.
> 🐛 Add dust_pillar particle type

- packages/json/src/index.ts
- packages/vscode-extension/mcmeta-language-configuration.json
- packages/vscode-extension/package.json
- packages/vscode-extension/resource/mcmeta.tmLanguage.json
- packages/vscode-extension/src/extension.mts
A dedicated `mcmeta` language is contributed. This will activate the extension automatically `onLanguage:mcmeta`, and start the language server when a user creates a `pack.mcmeta` in an empty workspace.
The language configuration is copied from https://github.com/microsoft/vscode/blob/main/extensions/json/language-configuration.json
- Fixes #1094
> ✨ Activate extension when creating pack.mcmeta

- packages/java-edition/src/binder/index.ts
- packages/java-edition/src/index.ts
- packages/java-edition/src/json/checker/index.ts
- packages/java-edition/src/mcfunction/checker/index.ts
This was caused by #1386, which added a `mcfunction:entry` binder, but this prevented the child binders from running. Changed so this logic happens in the checker, and the mcfunction entry checker now dispatches its children.
> 🚑️ Fix mcfunction binder

- __snapshots__/packages/java-edition/test-out/dependency/mcmeta.spec.js
- packages/java-edition/src/dependency/mcmeta.ts
The `minecraft:empty` loot table is not present in the vanilla data pack, it needs to be manually registered to the symbol table (assuming that it has existed at least since 1.15)
> 🐛 Register builtin empty loot table symbol

- packages/java-edition/src/mcfunction/checker/index.ts
- packages/java-edition/src/mcfunction/tree/argument.ts
- packages/java-edition/src/mcfunction/tree/patch.ts
Fixes #1403
With this, the list item definition is used instead for append and prepend.
We probably want to verify that the item returned by the path is actually a list. The type checking for the Nbt node is completely disabled when no list-like is found at the index.
Similarly, there is currently no error when trying to use data modify merge on anything else than a compound.
> 🐛 Fix data append and prepend using list definition instead of list item for type checking

- packages/core/src/common/externals/NodeJsExternals.ts
- packages/core/src/service/Downloader.ts
Two changes:
* Added an error hander on the nodejs downloader. Before this, the language server would crash when not connected to the network.
* ~~Allowed using the cache when fetching the checksum failed. This would allow using the cache both when offline and when the user is being rate limited by GitHub.~~
> 🐛 Allow downloader to use cache when offline

- packages/core/src/common/externals/NodeJsExternals.ts
- packages/core/src/common/externals/index.ts
- packages/java-edition/src/dependency/mcmeta.ts
- packages/java-edition/src/index.ts
- packages/java-edition/test/dependency/mcmeta.spec.ts
Before this PR, only a `pack.mcmeta` at the root of the project was detected to determine the loaded version. Now it searches up to a max depth of 2 folders, returning the first pack_format it can find.
> ✨ Scan the project root for pack.mcmeta files to determine version

- packages/mcdoc/src/runtime/attribute/builtin.ts
- packages/mcdoc/src/runtime/attribute/index.ts
- packages/mcdoc/src/runtime/completer/index.ts
- packages/nbt/src/checker/index.ts
- packages/nbt/src/completer/index.ts
- packages/nbt/src/node/index.ts
This was mentioned on discord while discussing #1415 
Json never has a predicate that requires specifying the namespace, so JSON remains unchanged
For SNBT, I save whether checking was using the isPredicate ruleset on the NBT node when attaching the mcdoc typeinfo.
For NBT paths, this is always true, similar to how NBT paths are always checked with the isPredicate ruleset.
There is a new mcdoc completer context now which extends the core completer context with an optional requireCannoical parameter.
> 🐛 Fix auto complete suggesting namespace-less entries with isPredicate

- package.json
This change was made in 2636999bd88ac7e033204756147ff74cad50a65d and I only noticed afterwards. I very often want to `clean:full` when switching between branches, mostly to clear out old test-out files. I don't want this to delete my node_modules. I see very few situations where I actually want to do that.
> 🔧 Don't clean node_modules

- packages/core/src/service/Project.ts
We got a report on discord where the stacktrace indicated that `isOnlyWatched` was being called from the `on fileModified` handler while `#dependencyFiles` was still undefined. The `fileModified` handler is attached in the contructor, while `#dependencyFiles` is only set during the `ready` phase, so this is not unexpected.
Is it better practice to just initialize these two as empty sets?
> 🐛 Fix crash when fileModified before dependencyFiles is set

- packages/core/src/node/ResourceLocationNode.ts
- packages/core/src/parser/resourceLocation.ts
- packages/core/src/processor/completer/builtin.ts
- packages/locales/src/locales/en.json
- packages/mcdoc/src/runtime/attribute/builtin.ts
Handles mcdoc with id attribute with `tags="required"` properly.
Example from dimension types: 
```
infiniburn: #[id(registry="block",tags="required")] string 
```
> ✨ Handle mcdoc `tags="required"` resource locations

- packages/mcdoc/src/runtime/checker/index.ts
- Fixes #1437 
Because NBT paths uses `unsafe` as their leaf type, this would cause a type mismatch when the nbt paths ended with an enum (or literal)
> 🐛 Fix nbt paths ending with an enum type

- __snapshots__/packages/core/test-out/processor/ColorInfoProvider.spec.js
- __snapshots__/packages/mcdoc/test-out/parser/syntax/attribute.spec.js
- packages/core/src/node/StringNode.ts
- packages/core/src/processor/ColorInfoProvider.ts
- packages/core/test/processor/ColorInfoProvider.spec.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- packages/mcdoc/src/runtime/attribute/builtin.ts
- packages/mcdoc/src/runtime/checker/error.ts
- packages/mcdoc/test/parser/index.spec.ts
> ✨ Add color information to JSON and NBT

- packages/mcdoc/src/runtime/checker/index.ts
Disclaimer: I made this on phone and didn't test it.
You may need to clear all cached data to see any effect.
> 🐛 Fix mapped types being cached and reused with different mappings

- packages/core/src/service/CacheService.ts
- packages/core/src/service/Downloader.ts
- packages/core/src/service/FileService.ts
- packages/core/src/service/Project.ts
- packages/core/src/service/Service.ts
- packages/core/test/utils.ts
- packages/java-edition/src/index.ts
Vscode would underline these quotes and that meant you couldn't ctrl+click these uris as expected from the output log.
Also added a `projectRoots` log entry
> 🔊 Remove quotes around logged URIs

- docs/user/config.adoc
- packages/core/src/common/externals/NodeJsExternals.ts
- packages/core/src/common/externals/index.ts
- packages/core/src/service/Config.ts
- packages/core/src/service/Project.ts
- closes #1414 
There hasn't been a noticeable performance drop in my (fairly large) project so I think this solution is more than good enough 🤷 
(if anyone wants to do some performance checks on this in voice chat with me I'd be more than happy to. not entirely sure what to check other than speed at which a file is re-parsed upon changing)
| before | after |
|-|-|
|![before renaming](https://github.com/user-attachments/assets/82ac9307-d19d-4e6d-b660-0779d8d42ead)|![after renaming](https://github.com/user-attachments/assets/bc793417-244f-458c-b949-7013b490f170)|
> 🐛 Enable `usePolling` on Windows to fix file-lock

- __snapshots__/packages/core/test-out/service/Config.spec.js
- packages/core/src/service/Config.ts
- packages/core/test/service/Config.spec.ts
while working on https://github.com/SpyglassMC/Spyglass/issues/1517, i realized that if you specified an empty object for `feature: {}`, it would effectively delete all other `env.feature` config properties.
example:
```ts
const base = {
env: {
feature: {
a: true,
b: true,
}
}
}
const override = {
env: {
feature: {},
}
}
const ans = ConfigService.merge(base, override)
// ans => `{ env: { feature: {} } }`
```
this is undesired behavior for a config system -- users should not need to specify every adjacent property to override a nested config setting
---
turns out there was an old `FIXME` to do this anyway. we have a `core.merge` method that behaves the way we want so I just hooked into it in this PR
> 🐛 Fix poor merge behavior of `Config` + overrides

- packages/core/src/service/Project.ts
This code was commented out in 5c3ce6cbc3492507c4d078aff4f47b3e595a5f4f by @SPGoding, but afaict nothing bad happens when I re-add it.
Files are re-checked, but unfortunately they aren't colorized nor do they get color information. Is there some way we can send that info to the client?
- Fixes #1510
> 🐛 Re-check client managed files after ready

- packages/java-edition/src/mcfunction/common/index.ts
> 🐛 Remove worldgen-only heightmaps from autocomplete

- package-lock.json
- packages/core/package.json
- packages/core/src/common/externals/BrowserExternals.ts
- packages/core/src/common/externals/NodeJsExternals.ts
- packages/core/src/common/externals/index.ts
- packages/core/src/service/FileService.ts
- packages/core/src/service/fileUtil.ts
- packages/java-edition/src/index.ts
> 🐛 Use custom file tree walker instead of globby

- packages/locales/src/locales/en.json
- packages/mcdoc/src/runtime/attribute/builtin.ts
Allows specifying a list of values that are not allowed in the `id` attribute, for example:
```rust
#[id(registry="item",exclude="air")] string
```
**Implementation note:**
I wasn't sure whether to put this in `ResourceLocationOptions` or not, so I decided to keep it exclusive to the `id` attribute handler for now. I'd be happy to move it though.
> ✨ Add `exclude` option to `id` mcdoc attribute

- packages/core/src/node/ResourceLocationNode.ts
- packages/core/src/processor/binder/builtin.ts
- packages/mcdoc/src/runtime/attribute/builtin.ts
Allows writing `#[id(registry="texture",path="entity/banner/")] string` to specify that the resource location's path should implicitly start in that folder.
Also removes the unnecessary restrictions to categories defined in `Symbol`. This will make it possible to reference custom resources defined in the config or entirely custom resources by using the API.
> ✨ Add support for implicit paths in `id` attribute

- packages/core/src/processor/ColorInfoProvider.ts
> 🐛 Fix composite argb color provider not wrapping to negatives

- packages/java-edition/src/mcfunction/tree/patch.ts
- Fixes #1521 
I think semantically this is not really a definition, it is just a reference with the "write" access type. But this seems to work the best for autocomplete for score holders
>  🐛Make `execute store ... score` define the score holder

- packages/core/src/service/FileService.ts
- packages/java-edition/src/index.ts
- Fixes #1213 
This happens when an archive (like `archive://mcmeta.tar.gz`) was previously in the symbol cache, but after a restart is no longer present. By treating this as an `ENOENT` error, it will prevent the log spam, and files will be treated as if they're not present.
> 🐛 Fix "archive has not been loaded in memory" log spam

- packages/java-edition/src/mcfunction/checker/index.ts
- packages/java-edition/src/mcfunction/node/argument.ts
Adds these two types to the list of particles requiring options, and also changes the checker to handle this more gracefully in the future.
The reason why we need this hardcoded list, is that otherwise we'd need to query mcdoc to determine something outside of JSON and SNBT, which we currently don't do yet. This could be changed in the future, but this is good enough for now.
> 🐛 Fix `block_crumble` and `trail` particles not allowing options

- packages/core/src/service/Config.ts
This is a workaround to fix undeclared warnings in data packs when the resource pack is not loaded. 
- Fixes #1663
As a side effect this will also hide these warnings for references in side resource packs, but there is currently not a great way to fix this without altering the config structure of the `undeclaredSymbol` rule.
> 🐛 Only show undeclaredSymbol warnings for data pack file categories

- packages/java-edition/src/dependency/mcmeta.ts
- packages/java-edition/src/index.ts
- packages/java-edition/test/dependency/mcmeta.spec.ts
- Fixes #1621
Doesn't fix the cause (some kind of config init failure?), but at least handles this gracefully.
> 🐛 Handle when config.env.gameVersion is undefined

- packages/core/src/service/Project.ts
> 🐛 Ensure cache root exists before opening it

- packages/core/src/service/Config.ts
- packages/mcdoc/src/runtime/checker/index.ts
- Fixes #1655
The config is disabled by default, because my estimate is that there are more people affected by corrupt caches than there are affected by performance issues due to huge NBT/JSON, since switching game versions is fairly common.
> 🐛 Add config to enable/disable mcdoc caching

- __snapshots__/packages/mcdoc/test-out/__fixture__/dispatcher/random_number_generator.spec.js
- packages/json/src/completer/index.ts
- packages/language-server/src/util/toLS.ts
- packages/mcdoc-cli/src/commands/locale.ts
- packages/mcdoc/src/binder/index.ts
- packages/mcdoc/src/common.ts
- packages/mcdoc/src/node/index.ts
- packages/mcdoc/src/runtime/completer/index.ts
- packages/mcdoc/src/type/index.ts
- packages/nbt/src/completer/index.ts
* Added a `desc` field to `McdocType` enum values containing their doc comment
* Replaced nested structs and enums with references during binding, because they are hoisted anyways
* Reduces the symbol cache file from 15.3M characters (1043KB gzipped) -> 14.9M characters (1006KB gzipped)
* Reduces the mcdoc-cli's export from 128K lines -> 88K lines
* Field documentation now shows up in autocomplete
> ✨ Mcdoc binding improvements

- packages/core/src/processor/colorizer/Colorizer.ts
- packages/core/src/symbol/Symbol.ts
- packages/discord-bot/src/index.ts
- packages/java-edition/src/json/binder/index.ts
- packages/java-edition/src/json/index.ts
- packages/java-edition/src/json/mcdocAttributes.ts
- packages/java-edition/src/json/node/index.ts
- packages/java-edition/src/json/parser/index.ts
- packages/vscode-extension/package.json
> ✨ Improve translation keys

- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftItemSlot.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftScoreboardSlot.spec.js
- packages/java-edition/src/mcfunction/mcdocAttributes.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
- Fixes #1685
Also improves error messages drastically in other literal arguments:
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/e7259414-a10f-42cd-870a-6379c7fd6f2c)|![image](https://github.com/user-attachments/assets/179c31d4-6c44-417f-ae17-5b40161caa9e)|
> 🐛 Improve command literal parsing

- packages/core/src/source/Source.ts
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
> 🐛 Fix score holders starting with `*`

- package-lock.json
- packages/core/package.json
- packages/core/src/service/CacheService.ts
- packages/core/src/service/Config.ts
- packages/core/src/service/Project.ts
- packages/java-edition/package.json
> 🐛 Fix exclude config behavior

- __snapshots__/packages/core/test-out/parser/record.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftBlockPredicate.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftBlockState.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftComponent.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftEntity.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftItemPredicate.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftItemStack.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftLootModifier.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftLootPredicate.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftLootTable.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftNbtCompoundTag.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftNbtTag.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftParticle.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftScoreHolder.spec.js
- __snapshots__/packages/java-edition/test-out/mcfunction/parser/argument/minecraftStyle.spec.js
- __snapshots__/packages/json/test-out/parser/object.spec.js
- __snapshots__/packages/nbt/test-out/parser/compound.spec.js
- __snapshots__/packages/nbt/test-out/parser/path.spec.js
- packages/core/src/node/RecordNode.ts
- packages/core/src/parser/record.ts
- packages/core/src/processor/completer/builtin.ts
- packages/java-edition/src/mcfunction/completer/argument.ts
- packages/java-edition/src/mcfunction/node/argument.ts
- packages/java-edition/src/mcfunction/parser/argument.ts
The code used to assume that the first and last characters in the range of a record node are the brackets. No completions would be suggested for key-value pairs when the cursor is at either end of the range, as that is assumed to be outside the brackets. However, this assumption is violated when there is no closing bracket, which is a common occurrence during editing for users who do not rely on their editor to automatically close brackets. This commit fixes the issue by keeping track of the actual range inside the brackets.
> 🐛 Fix completion inside unclosed records

- package-lock.json
- packages/core/package.json
- packages/core/src/service/Config.ts
- packages/core/src/service/Project.ts
- Switches to `picomatch`, this also fixes web support
- Set the correct options for picomatch where most patterns make sense
- Set some sensible defaults
> 🎨 Switch to picomatch

- .github/workflows/commit.yml
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> 💚 Update artifact actions to v4

- packages/core/src/service/CacheService.ts
- packages/core/src/service/Project.ts
Also slightly tweaks the auto-cache interval behavior. The timer will now only start when the project is ready, changed the interval from 10 minutes to 5 minutes, and the project will now be cached immediately after ready, instead of having to wait potentially 10 minutes.
> 🐛 Fix hash of binary files in cache service

- packages/discord-bot/src/index.ts
Idk why I'm doing this instead of something more useful
> Discord bot improvements

- packages/core/src/service/CacheService.ts
- packages/core/src/service/Context.ts
- packages/core/src/service/FileService.ts
- packages/core/src/service/MetaRegistry.ts
- packages/core/src/service/Project.ts
- packages/java-edition/src/binder/index.ts
- packages/java-edition/src/index.ts
- packages/java-edition/test/mcfunction/parser/argument.spec.ts
- packages/json/src/index.ts
(This PR could have each commit individually merged instead of a squash merge since I separated units of change into four individually revertable commits. Well after a `git rebase --autosquash -i 3ea96b` that is)
This PR adds an additional `uriPredicate` option to `LanguageOptions` during language registration. The `json` language definition has been updated to include a `uriPredicate` to ensure the JSON file actually belongs to a data pack or a resource pack. This check is more accurate than the `DocumentFilter` implemented client side in the VS Code extension as it takes the roots and the available file categories into consideration. Additions have also been made to `Project.shouldExclude()` to make sure unsupported files never go into the document life cycle.
This PR also fixes two …
> 🐛 Ignore non-Minecraft JSON files

- packages/mcdoc/src/runtime/checker/index.ts
The issue was that for a type like this:
```rust
type Foo = (
#[until="1.21.5"] #[canonical] Enchantments |
EnchantmentLevels |
)
```
The previous code would detect that one of the members has `#[canonical]` and filter out all the non-canonical members. This would end up simplifying the entire union to an empty union. The fix is to first filter members by other attributes (like `since` and `until`), and after that check if there are still canonical members.
> 🐛 Fix canonical union filtering when combined with other attribute filters

- __snapshots__/packages/java-edition/test-out/dependency/mcmeta.spec.js
- packages/java-edition/src/dependency/common.ts
- packages/java-edition/src/dependency/mcmeta.ts
- packages/java-edition/src/index.ts
- packages/java-edition/src/mcdocAttributes.ts
- packages/java-edition/test/dependency/mcmeta.spec.ts
- packages/locales/src/locales/en.json
- Now also looks at `supported_formats` and uses the highest value
- Now looks at all the pack.mcmeta files and uses the highest one
- Removes the warnings on `#[pack_format]` mcdoc types
- Fixes #1740
> ✨ Improve pack format detection

- __snapshots__/packages/mcfunction/test-out/parser/entry.spec.js
- __snapshots__/packages/mcfunction/test-out/parser/macro.spec.js
- packages/java-edition/src/mcfunction/mcdocAttributes.ts
- packages/mcfunction/src/colorizer/macro.ts
- packages/mcfunction/src/completer/index.ts
- packages/mcfunction/src/node/entry.ts
- packages/mcfunction/src/node/macro.ts
- packages/mcfunction/src/parser/entry.ts
- packages/mcfunction/src/parser/macro.ts
Adds support for `#[command(macro="implicit")]`. I had to modify the macro AST nodes to support macro nodes without the leading `$`.
> ✨ Implement macro option in command mcdoc attribute
